version: '3'

vars:
  OPENAPI_FILE: api/openapi/exchange_rates.yaml
  SWAGGER_FILE: docs/api/openapi/exchange_rates.yaml
  APP_IMAGE_TAG: micgos-web-app

tasks:
  default:
    cmds:
      - task --list
    desc: List all available tasks.

  build-image:
    desc: Build HTTP server Docker image using Dockerfile definition.
    cmds:
      - docker build -t {{.APP_IMAGE_TAG}} .

  test:
    desc: Run all unit tests with strict settings.
    cmds:
      - go test ./... -failfast -vet=all -count=1
    silent: true

  gen-code:
    desc: Generate server code and models from OpenAPI spec.
    cmds:
      - go generate ./...
    silent: true

  install-swagger-cli:
    desc: Install swagger-cli globally via npm.
    cmds:
      - npm install -g swagger-cli
    silent: true

  bundle-openapi:
    desc: Bundle OpenAPI spec and regenerate code.
    cmds:
      - task gen-code
      - swagger-cli bundle {{.OPENAPI_FILE}} -o {{.SWAGGER_FILE}} -t yaml
    silent: true

  env-up:
    desc: Validate and serve Swagger UI, Exchange Rates HTTP via Docker Compose.
    cmds:
      - task bundle-openapi
      - swagger-cli validate {{.OPENAPI_FILE}}
      - docker-compose up -d
    silent: true

  env-down:
    desc: Stop Swagger UI, Exchange Rates HTTP Docker containers.
    cmds:
      - docker-compose down
    silent: true

  clean:
    desc: Clean up generated Swagger files and stop containers.
    cmds:
      - docker-compose down || true
      - rm -f {{.SWAGGER_FILE}}
    silent: true