// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

// CryptoExchangeRateDTO defines model for CryptoExchangeRateDTO.
type CryptoExchangeRateDTO struct {
	Amount string `json:"amount"`
	From   string `json:"from"`
	To     string `json:"to"`
}

// ErrorDTO defines model for ErrorDTO.
type ErrorDTO struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GlobalExchangeRateDTO defines model for GlobalExchangeRateDTO.
type GlobalExchangeRateDTO struct {
	From string `json:"from"`
	Rate string `json:"rate"`
	To   string `json:"to"`
}

// GetCryptoExchangeRateParams defines parameters for GetCryptoExchangeRate.
type GetCryptoExchangeRateParams struct {
	From   string  `form:"from" json:"from"`
	To     string  `form:"to" json:"to"`
	Amount float64 `form:"amount" json:"amount"`
}

// GetGlobalExchangeRatesParams defines parameters for GetGlobalExchangeRates.
type GetGlobalExchangeRatesParams struct {
	Currencies string `form:"currencies" json:"currencies"`
}
